properties:
  resources:
    - resource: PSDscResources/Script
      id: sysinfo
      directives:
        description: Collect basic system & session evidence
        allowPrerelease: true
      settings:
        GetScript: |
          #"state"
        TestScript: |
          return $false
        SetScript: |
          try {
            $dir = "C:\Sample"
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
            $f = Join-Path $dir "sysinfo.txt"

            $who = whoami /all
            $ip  = ipconfig /all
            $ps  = Get-Process | Select-Object -First 20 Name,Id
            $t   = Get-Date

            "=== SYSINFO @ $t ==="        | Out-File $f
            "HOST: $env:COMPUTERNAME"     | Add-Content $f
            "USER: $env:USERNAME"         | Add-Content $f
            ""                            | Add-Content $f
            "== WHOAMI =="                | Add-Content $f
            $who                          | Add-Content $f
            ""                            | Add-Content $f
            "== IPCONFIG =="              | Add-Content $f
            $ip                           | Add-Content $f
            ""                            | Add-Content $f
            "== TOP PROCESSES =="         | Add-Content $f
            $ps | Out-String              | Add-Content $f
          } catch { "ERROR: $($_.Exception.Message)" | Out-File "C:\Sample\sysinfo.err" }
  configurationVersion: 0.2
