properties:
  resources:
    - resource: PSDscResources/Script
      id: notepad_curl_rundll
      directives:
        description: Start Notepad + curl code + rundll32 opens Google
        allowPrerelease: true
      settings:
        GetScript: |
          #"state"
        TestScript: |
          return $false
        SetScript: |
          try {
            $dir = "C:\Sample"
            New-Item -ItemType Directory -Path $dir -Force | Out-Null

            # 1) Notepad (widoczne okno/proces)
            Start-Process notepad.exe

            # 2) curl do internetu (szybko, bez zawieszania)
            try {
              $curl = Join-Path $env:SystemRoot "System32\curl.exe"
              if (Test-Path $curl) {
                $code = & $curl -s -o NUL -w "%{http_code}`n" https://www.google.com --max-time 5
                $code | Out-File (Join-Path $dir "curl_code.txt") -Encoding ASCII
              } else {
                [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                $resp = Invoke-WebRequest -Uri "https://www.google.com" -UseBasicParsing -TimeoutSec 5
                ($resp.StatusCode.ToString()) | Out-File (Join-Path $dir "curl_code.txt") -Encoding ASCII
              }
            } catch {
              ("NET-ERROR: " + $_.Exception.Message) | Out-File (Join-Path $dir "curl_code.txt")
            }

            # 3) rundll32 (LOLBIN) otwiera Google
            Start-Process rundll32.exe -ArgumentList "url.dll,FileProtocolHandler https://www.google.com"
          } catch {
            "ERROR: $($_.Exception.Message)" | Out-File (Join-Path $dir "config_error.log")
          }
  configurationVersion: 0.2
