properties:
  resources:
    - resource: PSDscResources/Script
      id: notepad_net_task_fast
      directives:
        description: Notepad + szybki test sieci + szybki scheduler (bez sleep)
        allowPrerelease: true
      settings:
        GetScript: |
          #"state"
        TestScript: |
          return $false
        SetScript: |
          try {
            # 1) Notepad (natychmiastowy, nie blokuje)
            Start-Process notepad.exe

            # 2) Bardzo szybki test sieci (DNS + TCP 443 z 3s timeout)
            try {
              $dns = (Resolve-DnsName -Name "www.google.com" -Type A -ErrorAction Stop |
                      Select-Object -First 1 -ExpandProperty IPAddress)
              $client = New-Object System.Net.Sockets.TcpClient
              $ar = $client.BeginConnect("www.google.com",443,$null,$null)
              [void]$ar.AsyncWaitHandle.WaitOne(3000)   # 3 sekundy
              if(-not $client.Connected){ $client.Close() }
            } catch { }

            # 3) Scheduler: utwórz i od razu usuń (bez czekania)
            try {
              $taskName = "WingetDemoLogon"
              $act  = New-ScheduledTaskAction -Execute "notepad.exe"
              $trig = New-ScheduledTaskTrigger -AtLogOn
              Register-ScheduledTask -TaskName $taskName -Action $act -Trigger $trig -Description "Winget demo" -Force | Out-Null
              Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
            } catch { }
          } catch { }
  configurationVersion: 0.2
