properties:
  resources:
    - resource: PSDscResources/Script
      id: open_notepad
      directives:
        description: Just run notepad.exe
        allowPrerelease: true
      settings:
        GetScript: |
          #"state"
        TestScript: |
          return $false
        SetScript: |
          try {
            Start-Process notepad.exe
          } catch {
            "ERROR: $($_.Exception.Message)" | Out-File "C:\Sample\notepad.err"
          }
  configurationVersion: 0.2
